### ISSUE TITLE
Feature Request: Points donations or trades

### ISSUE THREAD

**Issue by JJRcop** [tgstation/gbp-action#29]
I'd like to be able to donate my points to someone else. I imagine this being a special command in a pull request comment which allows people to donate to the author, for example `!!gbp donate 5`.

I also thought of a conditional donation that only applies when the pull request is merged, called a 'trade', like `!!gbp trade 10`. These trades can be kept track of in a bot-authored comment after the first trade is issued. Maybe donations should be skipped entirely, and just implement trades, to keep things simpler. A transfer fee, whether a percentage or static value, could also be considered.

Is this a good idea?

**Comment by optimumtact** [comment]
> Is this a good idea?

no

**Comment by Mothblocks** [comment]
I don't think this provides any benefits to GBP as a system.
